### ISSUE TITLE
Questions about the data load

### ISSUE THREAD

**Issue by jmdxp** [binarygraka/se-test-framework#1]
Hi Stefan,

Thanks for sharing this interesting gadget.
But when I try to run your gen_load_data.m in MATLAB, I found there is a undefined function 'load_prep_data'. So I just wonder if there should be a load_prep_data.m included in this MATLAB folder. Or could you please give some directions on how to preprocess those .csv data from NYISO?

**Comment by asayghe** [comment]
Hello
I got the same error it misses load_prep_data.m file

**Comment by JiweiTian** [comment]
Hello
I got the same error it misses load_prep_data.m file

**Comment by JiweiTian** [comment]
Did you solve this problem？ @jmdxp @asayghe

**Comment by su12345678900** [comment]
@JiweiTian @jmdxp @asayghe Did you solve this problem？I need you help！！
